#ifndef __AMAZON2_OHCI_H__
#define __AMAZON2_OHCI_H__

#define USBSEL        0x0800 // 1 --> host, 0 --> device
//0xF4000038 USB Host select
/*
 * USB Host Controller
 */
#define AMAZON2_USB_OFFSET        0xF0001400
#define HCREVISION              (AMAZON2_USB_OFFSET+0x00)
#define HCCONTROL               (AMAZON2_USB_OFFSET+0x04)
#define HCCOMMANDSTATUS         (AMAZON2_USB_OFFSET+0x08)
#define HCINTERRUPTSTATUS       (AMAZON2_USB_OFFSET+0x0C)
#define HCINTERRUPTENABLE       (AMAZON2_USB_OFFSET+0x10)
#define HCINTERRUPTDISABLE      (AMAZON2_USB_OFFSET+0x14)
#define HCHCCA                  (AMAZON2_USB_OFFSET+0x18)
#define HCPERIODCURRENTED       (AMAZON2_USB_OFFSET+0x1C)
#define HCCONTROLHEADED         (AMAZON2_USB_OFFSET+0x20)
#define HCCONTROLCURRENTED      (AMAZON2_USB_OFFSET+0x24)
#define HCBULKHEADED            (AMAZON2_USB_OFFSET+0x28)
#define HCBULKCURRENTED         (AMAZON2_USB_OFFSET+0x2C)
#define HCDONEHEAD              (AMAZON2_USB_OFFSET+0x30)
#define HCFMINTERVAL            (AMAZON2_USB_OFFSET+0x34)
#define HCFMREMAINING           (AMAZON2_USB_OFFSET+0x38)
#define HCFMNUMBER              (AMAZON2_USB_OFFSET+0x3C)
#define HCPERIODICSTART         (AMAZON2_USB_OFFSET+0x40)
#define HCLSTHRESHOLD           (AMAZON2_USB_OFFSET+0x44)
#define HCRHDESCRIPTORA         (AMAZON2_USB_OFFSET+0x48)
#define HCRHDESCRIPTORB         (AMAZON2_USB_OFFSET+0x4C)
#define HCRHSTATUS              (AMAZON2_USB_OFFSET+0x50)
#define HCRHPORTSTATUS0         (AMAZON2_USB_OFFSET+0x54)
#define HCRHPORTSTATUS1         (AMAZON2_USB_OFFSET+0x58)

#endif 
